#
# ローカル開発環境
#
version: '3'
services:

  pm2:
    build: ./docker/pm2
    container_name: pm2test_pm2_container
    depends_on:
      - node
    volumes:
      - .:/pm2

  # watch用のコンテナ
  node:
    build: ./docker/node
    container_name: pm2test_node_container
    tty: true
    volumes:
      - .:/pm2

  nginx:
    build: ./docker/nginx
    container_name: pm2test_nginx_container
    depends_on:
      - pm2
    ports:
      - 80:80
    volumes:
      - .:/pm2
